lang: en
title: Glenn Sweeney
email: glenn@glennsweeney.com
description: >-
  Glenn Sweeney's Homepage
baseurl: ""
url: ""

remote_theme: chrisrhymes/bulma-clean-theme

show_sidebar: false
hide_share_buttons: true
fixed_navbar: top

collections:
  projects: 
    output: true
