name: Build and deploy jekyll site

on:
  push:
    branches:
      - source

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: build
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
          format_output: true

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: master