name: Tests

on:
    pull_request:
        branches:
            - "**"

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: 24
                  cache: "npm"
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build
            - name: Unit Tests
              run: npm run test:unit
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: 24
                  cache: "npm"
            - name: Install dependencies
              run: npm ci
            - name: Lint
              run: npm run lint
